### ISSUE TITLE
Unable to send SMS

### ISSUE THREAD

**Issue by PanderMusubi** [keepalivedev/KeepAlive#2] opened 2023-12-17 14:19 UTC
I cannot send a TEST ALERT SMS even though I have a working SIM with SMS. I do have a second SIM which cannot send SMS, but it isn't configured by the device to send SMS.

Using lineage_instantnoodlep-userdebug 11 RQ3A.211001.001 518ed25ea9 (Android 11).

**Comment by keepalivedev** [comment] 2023-12-17 20:14
Are you able to set one of the SIMs as the default SMS subscription?  Unfortunately I do not have any dual SIM phones to test with but I am looking into a fix and the docs seem to indicate it should be using whichever is set as the default for SMS.  If there is no default it says it should pop up a dialog to let you choose... did it do that for you?

**Comment by PanderMusubi** [comment] 2023-12-17 22:08
I'm able to set it in Android Settings, but not in the app and the app never asked me.

**Comment by Gothico74** [comment] 2023-12-19 06:25
Hi. Just found your nice App. Can't send Test SMS also.
Single SIM. WiFi on/off did no change.
ForceClose and granting Phone Access Rights didn't either.

Xiaomi Mi 9 with MIUI 12, Android 10 (sucks I know),no root, Germany

**Comment by Gothico74** [comment] 2023-12-20 21:35
Sry, not for me.
Might be a MiUi restriction, don't know.
Added phonenumbers in national and international code, without luck.

**Comment by Mihails-Simvulidi** [comment] 2023-12-24 19:46
SMS sending doesn't work for me as well on Google Pixel 7, Android 14. There is a notification "Keep Alive Alert triggered! An SMS has been sent to your emergency contact(s): +371 [...]", but nothing is sent.

**Comment by keepalivedev** [comment] 2023-12-30 17:02
@Gothico74 @Mihails-Simvulidi Can you confirm if you are using the Google Play or F-droid stores or the release APKs?  Also, can you let me know if the Test Call button works?  I am thinking it might be an issue with international numbers but I am not sure, I appreciate the help troubleshooting this.

**Comment by Mihails-Simvulidi** [comment] 2023-12-30 17:18
I'm using Google Play. When I'm clicking the "TEST ALERT SMS" button, I'm getting a notification "Keep Alive Alert triggered! An SMS has been sent to your emergency contact(s): +371 [...]", but SMS isn't received (it also isn't present in the Messages app).

**Comment by Gothico74** [comment] 2023-12-30 20:39
1.05 from F-Droid and updated from GitHub to 1.06.
Phonenumbers are in international Format and the Button is not available/ highlighted.

**Comment by keepalivedev** [comment] 2024-01-13 16:48
@Gothico74 I assumed you were getting an error but you are saying the 'Test Alert SMS' button is not visible at all?  @PanderMusubi is this the case for you as well?

**Comment by Gothico74** [comment] 2024-01-13 18:21
Its visible but greyed out, not available

**Comment by keepalivedev** [comment] 2024-01-14 17:13
@Gothico74  @PanderMusubi I believe I have fixed the issue this time, can you try the latest release and let me know if that works? https://github.com/keepalivedev/KeepAlive/releases/tag/1.1.1

**Comment by Gothico74** [comment] 2024-01-14 18:07
Test Call: Phones are ringing
Test SMS: Sending SMS to Mobile

Check aaand Check

Working now

Featurerequest: the ability to enter alias for phonenumbers. I m very bad in remembering phonenumbers... 🤫

**Comment by PanderMusubi** [comment] 2024-01-17 13:29
I have created https://gitlab.com/fdroid/fdroiddata/-/issues/3171 so we can use the latest version on F-Droid.

**Comment by p-doyle** [comment] 2024-01-17 22:29
Thanks! It turns out that I forgot to increment the build version in the v1.0.6 release and so F-Droid didn't see it as a new version..  Moving forward it should update automatically I hope!

**Comment by keepalivedev** [comment] 2024-01-17 22:31
Thanks! It turns out that I forgot to update the build # in the v1.0.6 release and so F-Droid didn't see it as a new version... Moving forward it should update automatically though I hope!

**Comment by Mihails-Simvulidi** [comment] 2024-01-19 07:32
Installed version 1.1.1 from Google Play but SMS still cannot be sent. Debug log:
> 2024-01-19 07:26:36: Getting SMS manager with context.getSystemService
> 2024-01-19 07:26:36: checking for activity starting at 2024-01-17 07:28:09
> 2024-01-19 07:26:36: Current alarm set for 2024-01-19 15:19:29 local time
> 2024-01-19 07:26:36: Have all permissions
> 2024-01-19 07:26:33: Sending location message, string is GPS Coordinates: (56.[...], 24.[...]). Accuracy (m): 18.71. Possible address: [...], Latvia. 
> 2024-01-19 07:26:33: Sending text message to: +371[...]
> 2024-01-19 07:26:33: Getting SMS manager with context.getSystemService
> 2024-01-19 07:26:33: Sending alert SMS!
> 2024-01-19 07:26:25: Getting SMS manager with context.getSystemService
> 2024-01-19 07:26:25: checking for activity starting at 2024-01-17 07:28:09
> 2024-01-19 07:26:25: Current alarm set for 2024-01-19 15:19:29 local time
> 2024-01-19 07:26:25: Have all permissions

**Comment by keepalivedev** [comment] 2024-01-20 14:26
> Installed version 1.1.1 from Google Play but SMS still cannot be sent. Debug log:
> 
> > 2024-01-19 07:26:36: Getting SMS manager with context.getSystemService
> > 2024-01-19 07:26:36: checking for activity starting at 2024-01-17 07:28:09
> > 2024-01-19 07:26:36: Current alarm set for 2024-01-19 15:19:29 local time
> > 2024-01-19 07:26:36: Have all permissions
> > 2024-01-19 07:26:33: Sending location message, string is GPS Coordinates: (56.[...], 24.[...]). Accuracy (m): 18.71. Possible address: [...], Latvia.
> > 2024-01-19 07:26:33: Sending text message to: +371[...]
> > 2024-01-19 07:26:33: Getting SMS manager with context.getSystemService
> > 2024-01-19 07:26:33: Sending alert SMS!
> > 2024-01-19 07:26:25: Getting SMS manager with context.getSystemService
> > 2024-01-19 07:26:25: checking for activity starting at 2024-01-17 07:28:09
> > 2024-01-19 07:26:25: Current alarm set for 2024-01-19 15:19:29 local time
> > 2024-01-19 07:26:25: Have all permissions

Hmm... Most of my testing was done with a Pixel emulator on Android 14 so I am really confused as to why it's not working for you.  The logs look normal.  Can you try sending an SMS to yourself and see if that goes through?

**Comment by Mihails-Simvulidi** [comment] 2024-01-20 16:42
Do you mean manually in the Messages app? Yes, everything works fine. But in the KeepAlive app it doesn't.

**Comment by keepalivedev** [comment] 2024-01-20 21:00
I mean setting the phone number of your own device in the app and then trying to send a test SMS to yourself.

**Comment by Mihails-Simvulidi** [comment] 2024-01-20 21:14
Tried this, nothing is sent.

**Comment by Gothico74** [comment] 2024-01-21 12:11
> Tried this, nothing is sent.

Well the EM Call was placed in a second.
The SMS took a while; about a minute to send/receive. Might be a provider thing.
When placed, the App will notice you.
Tried a minute ago

**Comment by Mihails-Simvulidi** [comment] 2024-01-21 13:21
Received an SMS for the first time a few minutes ago with the text "Unable to determine location." (I have another alert message set up in settings). All permissions are granted. When I click "TEST ALERT SMS", still nothing happens.
![image](https://github.com/keepalivedev/KeepAlive/assets/52172784/a25ae65c-b7ab-4fa8-b2a3-4713f0dfa448)
![image](https://github.com/keepalivedev/KeepAlive/assets/52172784/c1324e3f-2b6f-4b16-96e8-700f1606ccd5)

**Comment by keepalivedev** [comment] 2024-01-21 13:29
Could you try disabling the 'Include Location' option and then try testing the SMS alert again?  It looks like it might be getting stuck trying to determine the location.

**Comment by Mihails-Simvulidi** [comment] 2024-01-21 14:13
I have found where there is an issue - if a message only contains ASCII symbols, then SMS is sent, even with location enabled. When there is any unicode symbol, the app doesn't send anything.

**Comment by PanderMusubi** [comment] 2024-01-21 14:21
Either convert the Unicode, prevent entering non-ASCII or prevent saving non-ASCII.

**Comment by Mihails-Simvulidi** [comment] 2024-01-21 14:41
It seems that the android.telephony.SmsManager method sendTextMessage which is used in the app doesn't support unicode and you need to use the sendMultipartTextMessage method instead.

**Comment by keepalivedev** [comment] 2024-01-21 17:30
> I have found where there is an issue - if a message only contains ASCII symbols, then SMS is sent, even with location enabled. When there is any unicode symbol, the app doesn't send anything.

Good catch!  It looks like the issue is that, when using unicode characters, the character limit is reduced to 70 instead of the normal 160.  And if a message is over the character limit it fails to send.  I've tested a fix and should have a new release available shortly.  Thanks!

**Comment by Mihails-Simvulidi** [comment] 2024-01-21 17:47
Maybe it's worth to use [PendingIntent](https://developer.android.com/reference/android/app/PendingIntent) parameters to ensure that SMS is sent and/or delivered and show some warning to the user if this didn't happen e.g. within 1 minute?

**Comment by keepalivedev** [comment] 2024-01-21 18:08
Yep that is part of the fix :)

**Comment by PanderMusubi** [comment] 2024-01-28 14:23
Version 1.1.1 on F-Droid with ASCII works for me. 😃

**Comment by PanderMusubi** [comment] 2024-01-31 17:15
Off-topic, but included this app in my overview of F-Droid apps https://github.com/panderMusubi/fdroid

**Comment by keepalivedev** [comment] 2024-02-08 22:49
It looks like 1.1.2 is now available in F-Droid but there was a bug reported right before I published 1.1.2 to Google Play so I decided to wait, the fix is in 1.1.3 and was published yesterday.  Thanks for all the help troubleshooting this!

**Closed by keepalivedev** 2024-02-08 22:49 UTC
